# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-09-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('reversion_log', '0003_auto_20190815_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputrequestrevision',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='input_logged_request_revision', to='reversion.Revision',
                                       verbose_name='revision'),
        ),
    ]
